name: CI Pipeline

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make install  # Assuming 'make install' installs dependencies

      - name: Run Linter
        run: make lint  # Runs linting

      - name: Run Formatting Check
        run: make format-check  # Ensures formatting is correct

      - name: Run Tests
        run: make test  # Runs tests
